"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
var dotenv_1 = require("dotenv");
var config_1 = require("prisma/config");
dotenv_1.default.config({ path: ".env" });

exports.default = (0, config_1.defineConfig)({
  schema: "prisma/schema.prisma",
  migrations: {
  path: "prisma/migrations",
  seed: "node ./prisma/seed.js"
},
  datasource: {
    url: process.env.DATABASE_URL
  }
});
